interface Node {kind:"element"|"text";tag?:string;attrs?:Record<string,string>;text?:string;children?:Node[];parent?:Node;order:number}
const VOID=new Set(["area","base","br","col","embed","hr","img","input","link","meta","param","source","track","wbr"]);
const RAW=new Set(["script","style","noscript","template"]);
function dec(s:string){return s.replace(/&(#x?[0-9a-f]+|amp|lt|gt|quot|apos|nbsp);/gi,(_,e)=>{if(e[0]==="#"){const h=e[1]?.toLowerCase()==="x";return String.fromCodePoint(parseInt(e.slice(h?2:1),h?16:10));}return ({amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" "} as any)[e.toLowerCase()]??_;});}
function attrs(raw:string){const out:Record<string,string>={};const re=/([^\s=/>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g;let m;while((m=re.exec(raw)))out[m[1].toLowerCase()]=dec(m[2]??m[3]??m[4]??"");return out;}
export function parseHtml(html:string){let order=0;const root:Node={kind:"element",tag:"#document",children:[],order:order++};const stack=[root];let i=0;const add=(n:Node)=>{const p=stack[stack.length-1];n.parent=p;p.children!.push(n);};
while(i<html.length){if(html.startsWith("<!--",i)){const e=html.indexOf("-->",i+4);i=e>=0?e+3:html.length;continue;}if(html[i]!=="<"){const e=html.indexOf("<",i);const end=e>=0?e:html.length;const t=dec(html.slice(i,end));if(t)add({kind:"text",text:t,order:order++});i=end;continue;}if(html.startsWith("<!",i)||html.startsWith("<?",i)){const e=html.indexOf(">",i+2);i=e>=0?e+1:html.length;continue;}if(html.startsWith("</",i)){const e=html.indexOf(">",i+2);if(e<0)break;const tag=html.slice(i+2,e).trim().split(/\s+/,1)[0].toLowerCase();for(let s=stack.length-1;s>0;s--){if(stack[s].tag===tag){stack.length=s;break;}}i=e+1;continue;}
const e=html.indexOf(">",i+1);if(e<0)break;const raw=html.slice(i+1,e);const self=/\/\s*$/.test(raw);const clean=raw.replace(/\/\s*$/,"").trim();const m=/^([^\s/>]+)([\s\S]*)$/.exec(clean);if(!m){i=e+1;continue;}const tag=m[1].toLowerCase();const n:Node={kind:"element",tag,attrs:attrs(m[2]??""),children:[],order:order++};add(n);i=e+1;if(RAW.has(tag)){const ci=html.toLowerCase().indexOf(`</${tag}`,i);if(ci<0){i=html.length;continue;}const ce=html.indexOf(">",ci);i=ce>=0?ce+1:html.length;continue;}if(!self&&!VOID.has(tag))stack.push(n);}
return root;}
export function textContent(n:Node):string{if(n.kind==="text")return n.text??"";if(n.tag==="br")return " ";const p=(n.children??[]).map(textContent).filter(Boolean);return n.tag==="tr"?p.join(" | "):p.join(" ");}
export type HtmlNode=Node;
